[package]
name = "tinybmp"
description = "No-std, low memory footprint BMP image loader"
version = "0.3.0"
authors = ["James Waples <james@wapl.es>"]
edition = "2018"
repository = "https://github.com/embedded-graphics/tinybmp"
documentation = "https://docs.rs/tinybmp"
categories = ["embedded", "no-std", "multimedia::images"]
keywords = ["graphics", "embedded-graphics", "bmp", "bitmap", "image"]
readme = "./README.md"
license = "MIT OR Apache-2.0"
exclude = [
    "/.github/",
    "/.circleci/",
    ".gitignore",
]

[badges]
circle-ci = { repository = "embedded-graphics/tinybmp", branch = "master" }

[[test]]
name = "embedded_graphics"

[dependencies]
embedded-graphics = "0.7.0"
nom = { version = "6.0.1", default-features = false }
